[#ftl]
[@b.grid items=taskList?sort_by(["course","code"]) var="clazz" sortable="false" style="border:0.5px solid #006CB2"]
  [@b.row]
    [@b.col width="5%" title="序号"]${clazz_index+1}[/@]
    [@b.col width="8%"  property="crn" title="课程序号"]${(clazz.crn)!}[/@]
    [@b.col width="10%" property="course.code" title="课程代码"/]
    [@b.col width="20%" property="course.name" title="课程名称"]
      [#if enableLinkCourseInfo]
       <a href="${ems.base}/edu/course/info/${clazz.course.id}" target="_blank">${clazz.course.name}</a>
      [#else]
        ${clazz.course.name}
      [/#if]
    [/@]
    [@b.col width="5%"  property="course.credits" title="学分"/]
    [@b.col width="13%" property="courseType.name" title="课程类别" /]
    [@b.col width="10%" title="授课教室"][@getTeacherNames clazz.teachers/][/@]
    [@b.col width="12%" title="第一次上课日期" ]
      [#if table.timePublished]${(clazz.schedule.firstDate?string("yyyy-MM-dd"))!}[#else]尚未发布[/#if]
    [/@]
    [@b.col width="7%"  title="修读类别" ]${takerMap.get(clazz).takeType.name} [#if takerMap.get(clazz).freeListening]<sup>免听</sup>[/#if][#t/][/@]
    [@b.col width="10%" property="remark" title="备注"]
        ${clazz.remark!} ${clazz.id}
      [#list clazz.schedule.sessions as s]${(s.places)!}[#sep]&nbsp;[/#list]
    [/@]
  [/@]
[/@]
