[#ftl]
[@b.grid items=grades var="grade" filterable="false"]
  [@b.row]
    [@b.col width="4%" title="序号"]${grade_index+1}[/@]
    [@b.col width="12%" title="学年学期"]${grade.semester.schoolYear} ${grade.semester.name}[/@]
    [@b.col width="40%" title="课程名称"]${grade.course.name}[/@]
    [@b.col width="19%" title="课程类别"]${grade.courseType.name}[/@]
    [@b.col width="5%" title="学分"]${(grade.course.credits)!}[/@]
    [#if grade?exists]
    [#assign style][#if grade.published]${grade.passed?string("","color:red")}[/#if][/#assign]
    [@b.col width="20%" title="成绩"][#if grade.published]${grade.scoreText!"--"}[#else]${b.text('grade.notPublished')}[/#if][/@]
    [/#if]
  [/@]
[/@]
<br>
